### ISSUE TITLE
`ArrayIndexOutOfBoundsException` on JVM

### ISSUE THREAD

**Issue by catap** [kcrypt/scala-blake3#39]
The stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 37 out of bounds for length 37
	at ky.korins.blake3.Output.rootBytes(Output.scala:81)
	at ky.korins.blake3.HasherImpl.done(HasherImpl.scala:202)
...
```
it happened when `rootBytes(..)` is called with:
 - `out` as `Array[Byte](37)`;
 - `off` is `0`;
 - `len` is `37`.

An issue happened inside this match:
```
        lim - pos match {
          case 1 =>

          case 2 =>

          case 3 =>

          case _ =>
        }
```
on `case _ =>` condition, after `pos += 1` it fails on `out(pos)`.

ENV:
 - scala-blake3: `2.8.0`
 - scala: `2.13.6`
 - JVM: `OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)` 
 
 Seems like a rare GC bug.

**Comment by catap** [comment]
Can't reproduce it since JVM was updated => close.
